"""Initial schema

Revision ID: 2644668fec12
Revises: 
Create Date: 2026-05-30 10:16:11.930887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2644668fec12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_balance_equiv', sa.Float(), nullable=False),
    sa.Column('max_risk_percent', sa.Float(), nullable=False),
    sa.Column('confidence_threshold', sa.Integer(), nullable=False),
    sa.Column('min_atr_percentile', sa.Integer(), nullable=False),
    sa.Column('min_rr_ratio', sa.Float(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('max_open_trades', sa.Integer(), nullable=False),
    sa.Column('consecutive_loss_pause', sa.Integer(), nullable=False),
    sa.Column('london_start_hour', sa.Integer(), nullable=False),
    sa.Column('london_end_hour', sa.Integer(), nullable=False),
    sa.Column('ny_start_hour', sa.Integer(), nullable=False),
    sa.Column('ny_end_hour', sa.Integer(), nullable=False),
    sa.Column('news_blackout_minutes', sa.Integer(), nullable=False),
    sa.Column('engine_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('broker_environment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_r', sa.Float(), nullable=True),
    sa.Column('suggestion_1_impact', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('suggestion_1_finding', sa.Text(), nullable=True),
    sa.Column('suggestion_1_recommendation', sa.Text(), nullable=True),
    sa.Column('suggestion_1_expected_impact', sa.Text(), nullable=True),
    sa.Column('suggestion_1_verify_by', sa.Text(), nullable=True),
    sa.Column('suggestion_1_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('suggestion_1_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('suggestion_1_rejection_reason', sa.Text(), nullable=True),
    sa.Column('suggestion_2_impact', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('suggestion_2_finding', sa.Text(), nullable=True),
    sa.Column('suggestion_2_recommendation', sa.Text(), nullable=True),
    sa.Column('suggestion_2_expected_impact', sa.Text(), nullable=True),
    sa.Column('suggestion_2_verify_by', sa.Text(), nullable=True),
    sa.Column('suggestion_2_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('suggestion_2_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('suggestion_2_rejection_reason', sa.Text(), nullable=True),
    sa.Column('suggestion_3_impact', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('suggestion_3_finding', sa.Text(), nullable=True),
    sa.Column('suggestion_3_recommendation', sa.Text(), nullable=True),
    sa.Column('suggestion_3_expected_impact', sa.Text(), nullable=True),
    sa.Column('suggestion_3_verify_by', sa.Text(), nullable=True),
    sa.Column('suggestion_3_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('suggestion_3_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('suggestion_3_rejection_reason', sa.Text(), nullable=True),
    sa.Column('raw_optimizer_response', sa.Text(), nullable=True),
    sa.Column('prompt_version_at_analysis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('granularity', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('trade_signals', sa.Integer(), nullable=False),
    sa.Column('wait_signals', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('breakevens', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_r_achieved', sa.Float(), nullable=True),
    sa.Column('total_pnl_dollars', sa.Float(), nullable=True),
    sa.Column('equity_end_of_day', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('win_rate_by_pattern', sa.Text(), nullable=True),
    sa.Column('win_rate_by_session', sa.Text(), nullable=True),
    sa.Column('win_rate_by_hour', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_template', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_r_achieved', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('session', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('skip_reason', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('price_at_signal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claude_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_verdict', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('parsed_confidence', sa.Integer(), nullable=True),
    sa.Column('parsed_direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('session', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('atr_percentile', sa.Float(), nullable=True),
    sa.Column('rsi_m15', sa.Float(), nullable=True),
    sa.Column('rsi_h1', sa.Float(), nullable=True),
    sa.Column('macd_hist_h1', sa.Float(), nullable=True),
    sa.Column('h4_ema20', sa.Float(), nullable=True),
    sa.Column('h4_ema50', sa.Float(), nullable=True),
    sa.Column('h4_ema200', sa.Float(), nullable=True),
    sa.Column('h4_alignment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('h1_ema20', sa.Float(), nullable=True),
    sa.Column('stoch_m15', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_table('pattern_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('planned_entry', sa.Float(), nullable=False),
    sa.Column('actual_entry', sa.Float(), nullable=True),
    sa.Column('slippage_pips', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit_1', sa.Float(), nullable=False),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('planned_rr', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('broker_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('pre_trade_analysis', sa.Text(), nullable=True),
    sa.Column('post_trade_analysis', sa.Text(), nullable=True),
    sa.Column('what_went_right', sa.Text(), nullable=True),
    sa.Column('what_went_wrong', sa.Text(), nullable=True),
    sa.Column('improvement_hint', sa.Text(), nullable=True),
    sa.Column('pattern_quality', sa.Integer(), nullable=True),
    sa.Column('execution_quality', sa.Integer(), nullable=True),
    sa.Column('market_conditions', sa.Text(), nullable=True),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_table('trade_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('exit_reason', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('pnl_pips', sa.Float(), nullable=True),
    sa.Column('pnl_dollars', sa.Float(), nullable=True),
    sa.Column('r_achieved', sa.Float(), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('max_adverse_excursion', sa.Float(), nullable=True),
    sa.Column('max_favorable_excursion', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_outcomes')
    op.drop_table('trade_journal')
    op.drop_table('trades')
    op.drop_table('pattern_events')
    op.drop_table('market_context')
    op.drop_table('claude_responses')
    op.drop_table('signals')
    op.drop_table('prompt_versions')
    op.drop_table('performance_stats')
    op.drop_table('improvements')
    op.drop_table('engine_config')
    # ### end Alembic commands ###
