"""Add ai_provider to EngineConfig

Revision ID: 7466dc29b339
Revises: 2644668fec12
Create Date: 2026-06-01 11:06:21.764570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7466dc29b339'
down_revision: Union[str, Sequence[str], None] = '2644668fec12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine_config', sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='claude'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine_config', 'ai_provider')
    # ### end Alembic commands ###
