"""add system to trades

Revision ID: 800be9a68ac2
Revises: c94f2b1cf60d
Create Date: 2026-07-06 06:54:17.302441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '800be9a68ac2'
down_revision: Union[str, Sequence[str], None] = 'c94f2b1cf60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('system', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('trades', 'locked_profit_pips',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'locked_profit_pips',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_column('trades', 'system')
    # ### end Alembic commands ###
