"""Add StraddlePair

Revision ID: c94f2b1cf60d
Revises: bab500cf87e5
Create Date: 2026-06-02 14:01:35.902513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c94f2b1cf60d'
down_revision: Union[str, Sequence[str], None] = 'bab500cf87e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('straddle_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('buy_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sell_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('buy_entry', sa.Float(), nullable=False),
    sa.Column('sell_entry', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cancellation_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('straddle_pairs')
    # ### end Alembic commands ###
